version: '3.9'
services:
  vite:
    build: ./my-portfolio/
    env_file:
      - .env
    container_name: vite
    ports:
      - 3000:3000
    volumes:
      - portfolio:/app/front

volumes:
  portfolio:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/my-portfolio'
